#############################################################################################
#@author erik.flores 
#@fecha 13/NOVIEMBRE/2017
#############################################################################################
#RUTA-UBICACION DEL ARCHIVO DE CONFIGURACION DEL log4j2
LOG4J2.SUBDIRECTORY=/resources/log4j2.xml
#############################################################################################
#PARAMETROS ORACLE
DB.ORACLEURL=jdbc:oracle:thin:@srvdbatm.atm.local:1521:srvbdatm
DB.DATABASE=srvbdatm
DB.ORACLEUSER=AXISCRTV
DB.ORACLEPASSWD=ENC2:h9zW4U93uC5nczxtyPC2sgqk1b6n6ydmBEcX3Cu8Ht/U5e0fMnM/ruM2Gxicopniwo7x8Ovn4IWtekTKVVeh/6E=
#############################################################################################
#PARAMETROS SQLSERVER
DB.MSSQLURL=jdbc:sqlserver://srv00rtv02.atm.local:1433;databaseName=db_smt_auditoria;encrypt=true;trustServerCertificate=true
DB.MSSQLDATABASE=db_smt_auditoria
DB.MSSQLSUSER=usr_reporte
DB.MSMSSQLPASSWD=ENC2:X5rBJaRClbM9RDbGSzXQhTAW1CE2fLq82gYWEBEKlOc1qgJFHJe6nYtpRQbLhdbiKvwUx3g=
#############################################################################################
#SENTENCIA A EJECUTAR
SQL.Q1=SELECT rtrim(ltrim(vt.Placa)) placa, vt.Visita, CASE  WHEN vt.Fecha_Checkpoint < '19000101' OR vt.Fecha_Checkpoint IS NULL THEN NULL ELSE vt.Fecha_Checkpoint END Fecha_Checkpoint, CASE  WHEN vt.Tomar_ESOUT < '19000101' OR vt.Tomar_ESOUT IS NULL THEN NULL ELSE vt.Tomar_ESOUT END Tomar_ESOUT, CASE  WHEN vt.Califica < '19000101' OR vt.Califica IS NULL THEN NULL ELSE vt.Califica END Califica, CASE  WHEN vt."Envio Resultados" < '19000101' OR vt."Envio Resultados" IS NULL THEN NULL ELSE vt."Envio Resultados" END Envio_Resultados FROM db_smt_auditoria.dbo.v_tiempos_2 as vt 
#SQL.Q1=SELECT rtrim(ltrim(vt.Placa)) placa, vt.Visita, CASE WHEN vt.Fecha_Checkpoint < '19000101' OR vt.Fecha_Checkpoint IS NULL THEN NULL ELSE CONVERT(varchar, vt.Fecha_Checkpoint, 111) + ' ' + CONVERT(varchar, vt.Fecha_Checkpoint, 108) END Fecha_Checkpoint, CASE WHEN vt.Tomar_ESOUT < '19000101' OR vt.Tomar_ESOUT IS NULL THEN NULL ELSE CONVERT(varchar, vt.Tomar_ESOUT, 111) + ' ' + CONVERT(varchar, vt.Tomar_ESOUT, 108) END Tomar_ESOUT, CASE WHEN vt.Califica < '19000101' OR vt.Califica IS NULL THEN NULL ELSE CONVERT(varchar, vt.Califica, 111) + ' ' + CONVERT(varchar, vt.Califica, 108) END Califica, CASE WHEN vt."Envio Resultados" < '19000101' OR vt."Envio Resultados" IS NULL THEN NULL ELSE CONVERT(varchar, vt."Envio Resultados", 111) + ' ' + CONVERT(varchar, vt."Envio Resultados", 108) END Envio_Resultados FROM db_smt_auditoria.dbo.v_tiempos_2 as vt  
#SQL.Q1=SELECT rtrim(ltrim(v_tiempos.Placa)) placa, v_tiempos.Visita, CASE datepart(yyyy,v_tiempos.Fecha_Checkpoint) WHEN 1753 THEN '' ELSE CONVERT(varchar, v_tiempos.Fecha_Checkpoint, 103) + ' ' + CONVERT(varchar, v_tiempos.Fecha_Checkpoint, 108) END Fecha_Checkpoint, CASE datepart(yyyy,v_tiempos.Tomar_ESOUT) WHEN 1753 THEN '' ELSE CONVERT(varchar, v_tiempos.Tomar_ESOUT, 103) + ' ' + CONVERT(varchar, v_tiempos.Tomar_ESOUT, 108) END Tomar_ESOUT, CASE datepart(yyyy,v_tiempos.Califica) WHEN 1753 THEN '' ELSE CONVERT(varchar, v_tiempos.Califica, 103) + ' ' + CONVERT(varchar, v_tiempos.Califica, 108) END Califica, CASE datepart(yyyy,v_tiempos."Envio Resultados") WHEN 1753 THEN '' ELSE CONVERT(varchar, v_tiempos."Envio Resultados", 103) + ' ' + CONVERT(varchar, v_tiempos."Envio Resultados", 108) END Envio_Resultados FROM db_smt_auditoria.dbo.v_tiempos_2 v_tiempos 
SQL.Q2=SELECT TO_CHAR(TRUNC(MAX(A.FEC_CHECKPOINT)), 'YYYY/MM/DD') FECHA_ULTIMO_REGISTRO FROM AXISATM.SCRTV_REVISIONES A 
SQL.Q3=INSERT INTO AXISATM.SCRTV_REVISIONES (PLACA, ID_VISITA, FEC_CHECKPOINT, FEC_TOMAR_ESOUT, FEC_CALIFICA, FE_ENVIO_RESULTADO) VALUES (?, ?, ?, ?, ?, ?) 
#SQL.Q3=INSERT INTO AXISATM.SCRTV_REVISIONES (PLACA, ID_VISITA, FEC_CHECKPOINT, FEC_TOMAR_ESOUT, FEC_CALIFICA, FE_ENVIO_RESULTADO)   
#############################################################################################
#INTERVALO DE TIEMPO PARA VERIFICACION DE EVENTOS (COMING SOON)
#SQL.INTERVALO=10 
#############################################################################################
#PASO POR PARAMETROS LAS FECHAS A PROCESAR. 
#CASO CONTRARIO SE ENVIAN EN BLANCO PARA QUE EL PROGRAMA CALCULE EL RANGO DE FECHAS
#QUE VA DESDE LA ULTIMA VEZ QUE SE REGISTR\u00d3 EN AXISATM.SCRTV_REVISIONES HASTA EL DIA ANTERIOR A LA FECHA ACTUAL
#FORMATO YYYY/MM/DD por ejemplo 2019/06/01
PARAM.FECHA_INICIO_PROCESO=
PARAM.FECHA_FIN_PROCESO=
#############################################################################################
#PARAMETROS NOTIFICACION POR CORREO
MAIL.HOST=act.atm.gob.ec
MAIL.PORT=587
MAIL.FROM=notificaciones.bdrtv@atm.gob.ec
MAIL.PASS=ENC2:u3fPEQxSaZw02BCgQ2DhHoaqjEeJBLMmJeqq+FRNtSKewaSoxEjKJdovzFvSPtIZYFp7QoRItQ==
MAIL.TO=erik.flores@atm.gob.ec;
MAIL.CC=
MAIL.BCC=
MAIL.SUBJECT=Log de revisiones de SCRTV hacia AXIS
MAIL.BODY=Informe de novedades del paso del log de revisiones del SCRTV a AXIS.<br>
#############################################################################################
